object_file_path: "../models/cup/cup.obj"
material_lib_path: "../models/cup/cup.mtl"
save_image_path: "../images/cup.png"
max_depth: 5
max_iteration: 10000
position: [0, 0.64, 0.52]
lookat: [0, 0.4, 0.3]
up: [0, 1, 0]
fov: 60
width: 512
height: 512