object_file_path: "../models/room/room.obj"
material_lib_path: "../models/room/room.mtl"
save_image_path: "../images/room.png"
max_depth: 5
max_iteration: 10000
position: [0, 0, 4]
lookat: [0, 0, 0]
up: [0, 1, 0]
fov: 50
width: 512
height: 512